security:
    password_hashers:
        App\Domain\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: login

    firewalls:
        api:
            request_matcher: App\Infrastructure\Security\ApiRequestMatcher
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Infrastructure\Security\BearerAuthenticator
    access_control:
        - { path: ^/v1/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
